# Generated by OPTAL Compiler
# DO NOT EDIT - This file is auto-generated

import sys
import os
import time
import json
import traceback
from typing import Any, Dict, List, Optional, Callable
from dataclasses import dataclass
from functools import wraps

import numpy
import torch

# OPTAL Runtime Utilities

__OPTAL_RESULT_PREFIX__ = "__OPTAL_RESULT__="

def _optal_env_json(name: str, default):
    raw = os.environ.get(name, "")
    if not raw:
        return default
    try:
        return json.loads(raw)
    except Exception:
        return default

def optal_emit_result(obj: Dict[str, Any]):
    # Single-line JSON for the Go runtime to parse
    sys.stdout.write(__OPTAL_RESULT_PREFIX__ + json.dumps(obj, ensure_ascii=False) + "\n")
    sys.stdout.flush()

@dataclass
class OptimizationPath:
    """Represents an optimization path with techniques and metrics"""
    path_id: str
    techniques: List[str]
    metrics: Dict[str, float]
    code: Callable


class GradedBenchmark:
    """Base class for graded benchmarks"""
    
    def __init__(self, name: str):
        self.name = name
        self.endpoints: Dict[str, Any] = {}
        self.results: Dict[str, float] = {}
    
    def run(self) -> Dict[str, float]:
        """Run the benchmark and return results"""
        raise NotImplementedError
    
    def record(self, key: str, value: float):
        """Record a benchmark result"""
        self.results[key] = value


class TechniqueRegistry:
    """Registry for optimization techniques"""
    
    _instance = None
    
    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
            cls._instance.techniques = {}
        return cls._instance
    
    def register(self, name: str, technique: Callable):
        """Register a technique"""
        self.techniques[name] = technique
    
    def get(self, name: str) -> Optional[Callable]:
        """Get a technique by name"""
        return self.techniques.get(name)

"""Set notebook settings and imports."""
import json
import time
from pathlib import Path
from warnings import warn
import numpy as np
import torch
from torch import nn, optim
from torch.nn import functional as F
from torch.nn.utils.parametrizations import weight_norm
from torch.utils.data import TensorDataset, DataLoader, random_split
from tqdm import tqdm
""" Set environment variables for CUDA debugging."""
"""Set torch device."""
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"{device=}\n")
if torch.cuda.is_available():
    print(f"Current GPU device: {torch.cuda.get_device_name(device)}\n")
    n_devices = torch.cuda.device_count()
    print("All GPU devices:")
    for i in range(n_devices):
        print(f"Device {i}: {torch.cuda.get_device_name(i)}")
"""Read in data."""
filepath = Path.cwd() / "data/tiny_shakespeare.txt"
with open(filepath) as f:
    text = f.read()
"""View some info about text."""
n_chars = len(text)
tokens = sorted(set(text))
vocab_sz = len(tokens)
print(f"{n_chars=}")
print(f"\n{vocab_sz=}")
print(f"\nTokens: {''.join(tokens)}")
print(f"\nFirst 100 chars of text:\n---\n\n{text[:100]}\n\n---")
"""Tokenize and save tokens to a file."""
token_to_int = {t: i for i, t in enumerate(tokens)}
int_to_token = {i: t for t, i in token_to_int.items()}
encode = lambda tokens: [token_to_int[t] for t in tokens]
decode = lambda ints: "".join([int_to_token[i] for i in ints])
print(encode("Hello, world!"))
print(decode(encode("Hello, world!")))
data = torch.tensor(encode(text), dtype=torch.long)
filepath = Path.cwd() / "data/tiny_shakespeare_tokens.txt"
with open(filepath, "w") as f:
    for tok in tokens:
        f.write("%s" % tok)
"""Motivating self-attention."""
ctx_len = 4  # context length
x = torch.randn(ctx_len, ctx_len)  # input sequence
w = torch.zeros(ctx_len, ctx_len)  # attention weights
tril = torch.tril(torch.ones(ctx_len, ctx_len))  # triangular mask for our weights
w = w.masked_fill(tril == 0, float("-inf"))  # mask out upper triangle (we can't access future info)
print(f"{w=}")
w = F.softmax(w, dim=1)  # convert weight values to probs
print(f"{w=}")
print(f"{x=}")
attn_out = w @ x  # weighted aggregation (sum) of past elements (can think of this as self-attn output)
print(f"{attn_out=}")
"""Self-attention for a Decoder."""
batch_sz, ctx_len, emb_dim = 4, 4, 8
head_sz = 2
x = torch.randn(batch_sz, ctx_len, emb_dim)
q = query(x)  # -> [batch_sz, ctx_len, head_sz]
k = key(x)
v = value(x)
print(f"{k_q_sim.shape=}")
print(f"{k_q_sim=}")
tril = torch.tril(torch.ones(ctx_len, ctx_len))  # mask out upper triangle (we can't access future info)
k_q_sim = k_q_sim.masked_fill(tril == 0, float("-inf"))
attn_weights = F.softmax(k_q_sim, dim=2)
print(f"{attn_weights.shape=}")
print(f"{attn_weights=}")
print(f"{attn_out.shape=}")
print(f"{attn_out=}")
"""Create a class for a head of a self-attention unit for a Decoder."""
class Head(nn.Module):
    """Self-attention head."""
    def __init__(self, head_sz, emb_dim):
        """Initialize key, query, value."""
        super().__init__()
        self.head_sz, self.emb_dim = head_sz, emb_dim

        self.key = nn.Linear(emb_dim, head_sz, bias=False)
        self.query = nn.Linear(emb_dim, head_sz, bias=False)
        self.value = nn.Linear(emb_dim, head_sz, bias=False)


        self.key = AdderLinear(emb_dim, head_sz, bias=False)
        self.query = AdderLinear(emb_dim, head_sz, bias=False)
        self.value = AdderLinear(emb_dim, head_sz, bias=False)

    def forward(self, x):
        """Compute self-attention output."""
        _batch_sz, ctx_len, _emb_dim = x.shape
        q = self.query(x)
        k = self.key(x)  # -> [batch_sz, ctx_len, head_sz]
        v = self.value(x)

        k_q_sim = q @ k.transpose(2, 1) / np.sqrt(self.head_sz)  # scaled attention to preserve k, q variance


        k_q_sim = -(q.unsqueeze(2) - k.unsqueeze(1)).abs().sum(-1) / np.sqrt(self.head_sz)  # scaled attention to preserve k, q variance

        tril = torch.tril(torch.ones(ctx_len, ctx_len)).to(device)  # mask out upper triangle (we can't access future info)
        k_q_sim = k_q_sim.masked_fill(tril == 0, float("-inf"))
        attn_weights = F.softmax(k_q_sim, dim=2)

        attn_out = attn_weights @ v  # weighted sum of values


        attn_out = -(attn_weights.unsqueeze(-1) - v.unsqueeze(2)).abs().sum(dim=2)  # weighted sum of values

        return attn_out
"""Multi-head self-attention for a Decoder."""
n_heads = 2
heads = nn.ModuleList([Head(head_sz, emb_dim) for _ in range(n_heads)]).to(device)
attn_outs = [head(x.to(device)) for head in heads]  # -> n_heads x [batch_sz, ctx_len, head_sz]
attn_out = torch.cat(attn_outs, dim=2)  # -> [batch_sz, ctx_len, n_heads * head_sz]
multi_attn_out = proj(attn_out)
print(f"{multi_attn_out.shape=}")
"""Create a class for multi-head self-attention for a Decoder."""
class MultiHead(nn.Module):
    """Multi-head self-attention."""
    def __init__(self, n_heads, head_sz, emb_dim):
        """Initialize heads."""
        super().__init__()
        self.n_heads, self.head_sz, self.emb_dim = n_heads, head_sz, emb_dim
        self.heads = nn.ModuleList([Head(head_sz, emb_dim) for _ in range(n_heads)])

        self.proj = nn.Linear(self.n_heads * self.head_sz, self.emb_dim)  # project back to `emb_dim`


        self.proj = AdderLinear(self.n_heads * self.head_sz, self.emb_dim)  # project back to `emb_dim`

    def forward(self, x):
        attn_outs = [head(x) for head in self.heads]
        attn_out = torch.cat(attn_outs, dim=2)  # concatenate across head dimension
        attn_out = self.proj(attn_out)
        return attn_out
"""Create a class for a Feedforward network that operates on attention outputs."""
class Feedforward(nn.Module):
    """Feedforward layer."""
    def __init__(self, emb_dim, ff_dim):
        """Initialize weights."""
        super().__init__()
        self.layers = nn.Sequential(

            nn.Linear(emb_dim, emb_dim * ff_dim), nn.ReLU(), nn.Linear(emb_dim * ff_dim, emb_dim)


            AdderLinear(emb_dim, emb_dim * ff_dim), nn.ReLU(), AdderLinear(emb_dim * ff_dim, emb_dim)

        )
    def forward(self, x):
        return self.layers(x)
"""Create a Transformer block: communication -> computation (self-attention + feedforward + res + norm)."""
class Block(nn.Module):
    """Transformer block: communication followed by computation."""
    def __init__(self, n_heads, head_sz, emb_dim, ff_dim, dropout):
        super().__init__()
        self.n_heads, self.head_sz, self.emb_dim, self.ff_dim = n_heads, head_sz, emb_dim, ff_dim
        self.self_attn_ln = nn.LayerNorm(emb_dim)  # layer norm pre self-attention
        self.self_attn = MultiHead(n_heads, head_sz, emb_dim)  # multi-head self-attention
        self.self_attn_dropout = nn.Dropout(dropout)  # dropout after self-attention
        self.ff_ln = nn.LayerNorm(emb_dim)  # layer norm pre feedforward
        self.ff = Feedforward(emb_dim, ff_dim)  # position-wise feedforward
        self.ff_dropout = nn.Dropout(dropout)  # dropout after feedforward
    def forward(self, x):
        x = x + self.self_attn_dropout(self.self_attn(self.self_attn_ln(x)))
        x = x + self.ff_dropout(self.ff(self.ff_ln(x)))
        return x
"""Create NanoGPT: Decoder-only Transformer."""
class NanoGPT(nn.Module):
    """NanoGPT: Decoder-only Transformer."""
    def __init__(
        self,
        n_tokens=vocab_sz,
        ctx_len=512,
        n_blocks=8,
        n_heads=10,
        head_sz=64,
        emb_dim=512,
        ff_dim=4,
        dropout=0.1,
    ):
        super().__init__()
        (
            self.n_tokens,
            self.ctx_len,
            self.n_blocks,
            self.n_heads,
            self.head_sz,
            self.emb_dim,
            self.ff_dim,
        ) = (n_tokens, ctx_len, n_blocks, n_heads, head_sz, emb_dim, ff_dim)
        if (emb_dim / n_heads / head_sz) != 1:
            warn(f"Ratio of n_heads and head_sz to emb_dim ({emb_dim / n_heads / head_sz}) is not 1")
        self.tok_emb = nn.Embedding(n_tokens, emb_dim)  # to learn token embeddings
        self.pos_emb = nn.Embedding(ctx_len, emb_dim)  # to learn positional embeddings
        self.blocks = nn.Sequential(  # Transformer blocks
            *[Block(n_heads, head_sz, emb_dim, ff_dim, dropout) for _ in range(n_blocks)]
        )
        self.f_ln = nn.LayerNorm(emb_dim)  # final layer norm
        self.f_dropout = nn.Dropout(dropout)  # final dropout

        self.out = nn.Linear(emb_dim, n_tokens)


        self.out = AdderLinear(emb_dim, n_tokens)

        self.apply(self.xavier_init)
    def xavier_init(module, gain=1):
        """Applies Xavier initialization to all linear and embedding layer weights."""
        if isinstance(module, (nn.Linear, AdderLinear)) or isinstance(module, nn.Embedding):
            nn.init.xavier_normal_(module.weight, gain=gain)
    def forward(self, x):
        batch_sz, ctx_len = x.shape
        tok_emb = self.tok_emb(x)  # -> [batch_sz, ctx_len, emb_dim]
        pos_emb = self.pos_emb.weight[0:ctx_len]  # -> [ctx_len, emb_dim]
        pos_enc = tok_emb + pos_emb  # -> [batch_sz, ctx_len, emb_dim]
        logits = self.out(self.f_dropout(self.f_ln(self.blocks(pos_enc))))
        return logits
"""Create a function for generating output from the model."""
def generate(model, tokens, in_txt=None, n_tokens=100, temp=1.0, top_k=None, seed=42, print_gen=True):
    """Generate text from a nanoGPT model."""
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    token_to_int = {t: i for i, t in enumerate(tokens)}
    int_to_token = {i: t for t, i in token_to_int.items()}
    if in_txt is not None:
        encode = lambda tokens: [token_to_int[t] for t in tokens]
        in_tkns = encode(in_txt)
        input_len = len(in_tkns)
        x = torch.zeros((input_len + n_tokens,), dtype=torch.long).to(device)
        x[:input_len] = torch.tensor(in_tkns, dtype=torch.long).to(device)
    else:
        x = torch.zeros((1 + n_tokens,), dtype=torch.long).to(device)
        x[0] = token_to_int["\n"]
        input_len = 1
    assert len(x) <= model.ctx_len, (
        f"Generated length {len(x) + n_tokens} would exceed model context length {model.ctx_len}."
    )
    model.eval()
    with torch.no_grad():
        first_gen_idx, last_gen_idx = input_len - 1, input_len + n_tokens - 1
        for i in range(first_gen_idx, last_gen_idx):  # start gen after `input_len`
            model_first_ctx = 0 if i < model.ctx_len else i - model.ctx_len + 1
            logits = model(x[model_first_ctx:(i + 1)].unsqueeze(0))  # feed in `x` with a batch_sz of 1
            logits = logits[:, -1, :] / temp
            if top_k is not None:  # limit to top_k most likely tokens
                top_vals, top_idxs = logits.topk(top_k, dim=1)
                probs = F.softmax(top_vals, dim=1)  # compute top_k probs
                next_tkn_int = top_idxs.gather(1, torch.multinomial(probs, 1))  # sample top_k probs
            else:
                probs = F.softmax(logits, dim=1)  # compute probs for all tokens
                next_tkn_int = torch.multinomial(probs, 1)  # sample from probs
            x[i + 1] = next_tkn_int
            if print_gen:
                print(int_to_token[next_tkn_int.item()], end="")
    decode = lambda ints: "".join([int_to_token[i] for i in ints])
    return decode(x.tolist())
"""Build model, view its layers and parameters, and sample generation."""
nanogpt = NanoGPT().to(device)
print(nanogpt)
n_params_tot = 0
for name, parameter in nanogpt.named_parameters():
    if not parameter.requires_grad:
        continue
    n_params = parameter.numel()
    print(f"{name=}: {n_params=}")
    n_params_tot += n_params
print(f"\n{n_params_tot / 1e6} M parameters total\n")
print("Generating sample...\n")
in_txt = (
    "Wherefore art thou, Romeo? "
    "We are such stuff as dreams are made on. "
    "The course of true love never did run smooth."
)
gen = generate(nanogpt, tokens, in_txt=in_txt, n_tokens=200)
"""Create a DataLoader."""
def build_dataset(txtfile, ctx_len):
    """Build dataset from text file."""
    with open(txtfile) as f:
        text = f.read()
    tokens = sorted(list(set(text)))
    token_to_int = {t: i for i, t in enumerate(tokens)}
    encode = lambda tokens: [token_to_int[t] for t in tokens]
    data = torch.tensor(encode(text), dtype=torch.long)
    n_chars = len(text)
    n_examples = n_chars - ctx_len
    idxs = torch.arange(ctx_len + 1).unsqueeze(0) + torch.arange(n_examples).unsqueeze(1)
    X, Y = data[idxs[:, :-1]], data[idxs[:, 1:]]
    return X, Y
X, Y = build_dataset(Path.cwd() / "data/tiny_shakespeare.txt", nanogpt.ctx_len)
dataset = TensorDataset(X, Y)
train_data, test_data, val_data = random_split(dataset, [0.9, 0.05, 0.05])
batch_sz = 32
train_loader = DataLoader(train_data, batch_size=batch_sz, shuffle=True)
val_loader = DataLoader(val_data, batch_size=batch_sz, shuffle=True)
test_loader = DataLoader(test_data, batch_size=batch_sz, shuffle=True)
"""Create a train function."""
def apply_gradient_centralization(optimizer):
    """Applies gradient centralization to the optimizer.
    This function should be called before optimizer.step() in the training loop.
    """
    for group in optimizer.param_groups:
        for param in group["params"]:
            if param.grad is not None:
                grad_mean = param.grad.data.mean(dim=tuple(range(1, len(param.grad.shape))), keepdim=True)
                param.grad.data -= grad_mean
def train(
    model: nn.Module,  # model
    train_loader: DataLoader,  # batched dataset for training
    val_loader: DataLoader,  # batched dataset for validation
    optimizer: optim,  # optimizer
    loss_fn: nn.modules.loss,  # loss function
    max_epochs: int = 2,  # max n training epochs
    max_batches: int = 1e9,  # max n batches to train
    val_chk_interval: int = 200,  # check val loss every `val_chk_interval` batches and print losses
    val_iter: int = 5,  # number of batches on val_loader to run and avg when computing val loss
    patience_thresh: int = 1e9,  # consecutive batches without val loss decrease for early stopping
    save_chkpt_dir: str = "",  # dir to save model checkpoint
    save_chkpt_thresh: float = 0.5,  # save model checkpoint every `save_chkpt_interval` loss decrease
) -> tuple[torch.Tensor, np.ndarray, np.ndarray]:  # -> loss, train_losses, val_losses
    """Trains a model, returns loss."""
    def print_losses(epoch, batch_i, train_losses_avg, val_losses_avg):
        """Print current average losses."""
        print(
            f"Epoch {epoch + 1}: Batch {batch_i + 1}:  "
            f"Loss = {train_losses_avg[-1]:.3f}, Val Loss = {val_losses_avg[-1]:.3f}"
        )
.no_grad()
    def estimate_losses(model, val_loader, val_losses, val_losses_avg, train_losses, train_losses_avg):
        """Estimate losses on val_loader, and return val loss and train loss avg."""
        model.eval()
        for val_i, (x_val, y_val) in enumerate(val_loader):
            logits = model(x_val.to(device))
            val_loss = loss_fn(logits.view(-1, n_tokens), y_val.to(device).view(-1))
            val_losses.append(val_loss.item())
            if val_i >= (val_iter - 1):
                break
        val_losses_avg.append(np.mean(val_losses[-val_iter:]))
        train_losses_avg.append(np.mean(train_losses[-val_chk_interval:]))
        model.train()
    ctx_len, n_tokens  = model.ctx_len, model.n_tokens
    batch_sz, n_batches = train_loader.batch_size, len(train_loader)
    batch_lim = min(max_batches, n_batches * max_epochs)
    patience_thresh *= val_chk_interval  # convert to batches within model validation block
    train_losses, val_losses, train_losses_avg, val_losses_avg = [], [], [], []
    init_loss, best_val_loss = float("inf"), float("inf")
    patience_ct = 0
    for epoch in range(max_epochs):
        pbar = tqdm(enumerate(train_loader), total=batch_lim, desc="Batch progression")  # tqdm progress bar
        for batch_i, (x_train, y_train) in pbar:
            optimizer.zero_grad()
            logits = model(x_train.to(device))  # -> [batch_sz, ctx_len, n_tokens], but...
            loss = loss_fn(logits.view(-1, n_tokens), y_train.to(device).view(-1))
            loss.backward()
            apply_gradient_centralization(optimizer)
            optimizer.step()
            train_losses.append(loss.item())
            if val_chk_interval and batch_i % val_chk_interval == 0:
                estimate_losses(
                    model, val_loader, val_losses, val_losses_avg, train_losses, train_losses_avg
                )
                print_losses(epoch, batch_i, train_losses_avg, val_losses_avg)
                pbar.set_postfix_str(f"Total Batch {(batch_i + 1) * (epoch + 1)} / {batch_lim}")
                patience_ct = (
                    0 if val_losses_avg[-1] < best_val_loss else patience_ct + val_chk_interval
                )
                best_val_loss = min(best_val_loss, val_losses_avg[-1])
                if patience_ct >= patience_thresh:
                    print("Early stopping.")
                    print_losses(epoch, batch_i, train_losses_avg, val_losses_avg)
                    return loss, train_losses_avg, val_losses_avg
            if (batch_i + 1) * (epoch + 1) >= max_batches:
                print("Finished training:")
                print_losses(epoch, batch_i, train_losses_avg, val_losses_avg)
                return loss, train_losses_avg, val_losses_avg
            if (Path(save_chkpt_dir).exists()) and (init_loss - loss.item() > save_chkpt_thresh):
                torch.save(model.state_dict(), Path(save_chkpt_dir) / f"model_chkpt_loss{loss.item():.3f}.pth")
                init_loss = loss.item()
    print("Finished training:")
    print_losses(epoch, batch_i, train_losses_avg, val_losses_avg)
    return loss, train_losses_avg, val_losses_avg
"""Train and eval for just a few batches."""
save_chkpt_dir = Path.cwd() / "models/shakespeare_chkpts"
adam = torch.optim.AdamW(nanogpt.parameters(), lr=1e-3)
loss_fn = nn.CrossEntropyLoss()
loss, train_losses, val_losses = train(
    nanogpt, train_loader, val_loader, adam, loss_fn, max_batches=1000, save_chkpt_dir=save_chkpt_dir
)
"""Post-training generation."""
in_txt = (
    "Wherefore art thou, Romeo? "
    "We are such stuff as dreams are made on. "
    "The course of true love never did run smooth."
)
gen = generate(nanogpt, tokens, in_txt=in_txt, n_tokens=200, top_k=50, temp=0.5, seed=42)
"""Save / load model."""
torch.save(nanogpt.state_dict(), Path.cwd() / "models/nanogpt_shakespeare.pth")
with open(Path.cwd() / "models/nanogpt_shakespeare_config.json", "w") as f:
    json.dump(model_config, f)
time.sleep(1)
with open(Path.cwd() / "models/nanogpt_shakespeare_config.json", "w") as f:
    model_config = json.load(f)
nanogpt = NanoGPT(
    n_tokens=model_config["n_tokens"],
    ctx_len=model_config["ctx_len"],
    n_blocks=model_config["n_blocks"],
    n_heads=model_config["n_heads"],
    head_sz=model_config["head_sz"],
    emb_dim=model_config["emb_dim"],
    ff_dim=model_config["ff_dim"],
    dropout=model_config["dropout"],
).to(device)
nanogpt.load_state_dict(torch.load((Path.cwd() / "models/nanogpt_shakespeare.pth")))
# Implementation: Model_matmul
def impl_Model_matmul():
    global query, key, value

    query = nn.Linear(emb_dim, head_sz, bias=False)
    key = nn.Linear(emb_dim, head_sz, bias=False)
    value = nn.Linear(emb_dim, head_sz, bias=False)
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_matmul():
    return impl_Model_matmul()

# Register technique
TechniqueRegistry().register("Model_matmul", Model_matmul)

# Implementation: Model_addernetmatmul
def impl_Model_addernetmatmul():
    global query, key, value

    query = AdderLinear(emb_dim, head_sz, bias=False)
    key = AdderLinear(emb_dim, head_sz, bias=False)
    value = AdderLinear(emb_dim, head_sz, bias=False)
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_addernetmatmul():
    return impl_Model_addernetmatmul()

# Register technique
TechniqueRegistry().register("Model_addernetmatmul", Model_addernetmatmul)

# Implementation: Model_matmul
def impl_Model_matmul():
    global k_q_sim

    k_q_sim = q @ k.transpose(2, 1) / np.sqrt(head_sz)
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_matmul():
    return impl_Model_matmul()

# Register technique
TechniqueRegistry().register("Model_matmul", Model_matmul)

# Implementation: Model_addernetmatmul
def impl_Model_addernetmatmul():
    global k_q_sim

    k_q_sim = -(q.unsqueeze(2) - k.unsqueeze(1)).abs().sum(-1) / np.sqrt(head_sz)
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_addernetmatmul():
    return impl_Model_addernetmatmul()

# Register technique
TechniqueRegistry().register("Model_addernetmatmul", Model_addernetmatmul)

# Implementation: Model_matmul
def impl_Model_matmul():
    global attn_out

    attn_out = attn_weights @ v  # weighted sum of values
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_matmul():
    return impl_Model_matmul()

# Register technique
TechniqueRegistry().register("Model_matmul", Model_matmul)

# Implementation: Model_addernetmatmul
def impl_Model_addernetmatmul():
    global attn_out

    attn_out = -(attn_weights.unsqueeze(-1) - v.unsqueeze(2)).abs().sum(dim=2)  # weighted sum of values
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_addernetmatmul():
    return impl_Model_addernetmatmul()

# Register technique
TechniqueRegistry().register("Model_addernetmatmul", Model_addernetmatmul)

# Implementation: Model_matmul
def impl_Model_matmul():
    global proj

    proj = nn.Linear(n_heads * head_sz, emb_dim).to(device)  # project back to emb_dim
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_matmul():
    return impl_Model_matmul()

# Register technique
TechniqueRegistry().register("Model_matmul", Model_matmul)

# Implementation: Model_addernetmatmul
def impl_Model_addernetmatmul():
    global proj

    proj = AdderLinear(n_heads * head_sz, emb_dim).to(device)  # project back to emb_dim
    # OPTAL: Optimized based on @Use token configuration

# Wrapper for technique execution
def Model_addernetmatmul():
    return impl_Model_addernetmatmul()

# Register technique
TechniqueRegistry().register("Model_addernetmatmul", Model_addernetmatmul)

# Main execution
def main():
    """Main entry point for OPTAL generated program"""
    path_id = os.environ.get("OPTAL_PATH_ID", "optal_default")
    techniques_env = _optal_env_json("OPTAL_TECHNIQUES_JSON", [])
    benchmark_mode = os.environ.get("OPTAL_BENCHMARK_MODE", "strict").strip().lower()
    best_effort = (benchmark_mode == "best_effort")
    started = time.time()
    metrics: Dict[str, float] = {}
    benchmarks_out: Dict[str, Any] = {}
    
    try:
        # Execute impl techniques (registry order is made deterministic)
        registry = TechniqueRegistry()
        for name in sorted(registry.techniques.keys()):
            fn = registry.techniques[name]
            if callable(fn):
                fn()

        # Execute benchmarks
        for obj in list(globals().values()):
            if isinstance(obj, type) and issubclass(obj, GradedBenchmark) and obj is not GradedBenchmark:
                bench = obj()
                if best_effort:
                    try:
                        out = bench.run()
                    except Exception as e:
                        # Keep going; record failure for this benchmark
                        benchmarks_out[str(bench.name)] = {"__error__": str(e), "__traceback__": traceback.format_exc()}
                        continue
                else:
                    out = bench.run()
                if isinstance(out, dict):
                    # merge numeric metrics into flat map
                    for k, v in out.items():
                        if isinstance(v, (int, float)):
                            metrics[str(k).lower()] = float(v)
                    benchmarks_out[str(bench.name)] = out

        ended = time.time()
        optal_emit_result({
            "path_id": path_id,
            "techniques": techniques_env,
            "status": "ok",
            "metrics": metrics,
            "benchmarks": benchmarks_out,
            "elapsed_ms": int((ended - started) * 1000),
        })
    except Exception as e:
        ended = time.time()
        optal_emit_result({
            "path_id": path_id,
            "techniques": techniques_env,
            "status": "error",
            "error": str(e),
            "benchmarks": benchmarks_out,
            "elapsed_ms": int((ended - started) * 1000),
            "meta": {"traceback": traceback.format_exc()},
        })


if __name__ == "__main__":
    main()
